name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
  # Absence of the branches property under pull_request means it will apply to all branches

jobs:
  lint-test:
    uses: ./.github/workflows/workflow-lint-test-node.yml

  build:
    # if: github.ref == 'refs/heads/main'
    needs: lint-test
    uses: ./.github/workflows/workflow-build-container.yml
    with:
      container-name: ${{ github.event.repository.name }}
      tag: ${{ github.sha }}    
    secrets: inherit

  deploy:
    # if: github.ref == 'refs/heads/main'
    needs: build
    uses: ./.github/workflows/workflow-deploy-gcp.yml
    with:
      container-name: ${{ github.event.repository.name }}
      tag: ${{ github.sha }}
    secrets: inherit
  